#!/usr/bin/env python3
"""Record localization work in core-assets (cross-platform, stdlib only).

This is the localization work queue. When product Help, manuals, or
must-localize strings are added or changed, a work item is recorded here
so translators see new work instead of discovering it by accident.

Usage (from the core-assets repo root, or pass --root):

  python3 scripts/localization-work/localization_work.py add --id docs.auditor-setup-guide ...
  python3 scripts/localization-work/localization_work.py record --id docs.auditor-setup-guide --source-file PATH
  python3 scripts/localization-work/localization_work.py record-all
  python3 scripts/localization-work/localization_work.py render
  python3 scripts/localization-work/localization_work.py list

No pip packages. No environment variables. Catalogs stay LF.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import date
from pathlib import Path
from typing import Any

QUEUE_REL = Path("content/localization-work/queue.json")
SURFACES_REL = Path("content/localization-work/surfaces.json")
MARKDOWN_REL = Path("content/localization-work/queue.md")


def today() -> str:
    return date.today().isoformat()


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_json(path: Path, default: Any) -> Any:
    if not path.is_file():
        return default
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8", newline="\n")


def find_item(queue: dict[str, Any], item_id: str) -> dict[str, Any] | None:
    for item in queue.get("items", []):
        if item.get("id") == item_id:
            return item
    return None


def upsert_item(queue: dict[str, Any], incoming: dict[str, Any]) -> str:
    existing = find_item(queue, incoming["id"])
    if existing is None:
        queue.setdefault("items", []).append(incoming)
        return "added"
    existing.update({k: v for k, v in incoming.items() if v is not None})
    existing["updated"] = today()
    return "updated"


def render_markdown(queue: dict[str, Any]) -> str:
    lines = [
        "# Localization work queue",
        "",
        "Open items are work for language packs. Agent draft catalogs do",
        "**not** close an item. Close only when the required tags are",
        "reviewed and complete.",
        "",
        "Machine source: `queue.json`. Regenerated by",
        "`scripts/localization-work/localization_work.py render`.",
        "",
    ]
    items = list(queue.get("items", []))
    open_items = [i for i in items if i.get("status") == "open"]
    closed_items = [i for i in items if i.get("status") != "open"]
    lines.append(f"Open: **{len(open_items)}**. Closed: {len(closed_items)}.")
    lines.append("")
    lines.append("| ID | Status | Title | Source | Required tags | Notes |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for item in items:
        source = item.get("source_path", "")
        if item.get("source_repo"):
            source = f"{item['source_repo']}/{source}"
        notes = (item.get("notes") or "").replace("|", "/")
        tags = ", ".join(item.get("required_tags") or [])
        lines.append(
            f"| `{item.get('id', '')}` | {item.get('status', '')} | "
            f"{item.get('title', '')} | `{source}` | {tags} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def cmd_add(root: Path, args: argparse.Namespace) -> int:
    queue_path = root / QUEUE_REL
    queue = load_json(queue_path, {"version": 1, "items": []})
    source_sha = None
    if args.source_file:
        source_path = Path(args.source_file)
        if not source_path.is_file():
            print(f"source file not found: {source_path}", file=sys.stderr)
            return 2
        source_sha = sha256_file(source_path)
    item = {
        "id": args.id,
        "status": args.status,
        "priority": args.priority,
        "kind": args.kind,
        "title": args.title,
        "added": today(),
        "updated": today(),
        "source_repo": args.source_repo,
        "source_path": args.source_path,
        "source_sha256": source_sha,
        "product_route": args.product_route,
        "required_tags": args.required_tags,
        "draft_tags": args.draft_tags,
        "notes": args.notes,
    }
    action = upsert_item(queue, item)
    write_json(queue_path, queue)
    (root / MARKDOWN_REL).write_text(render_markdown(queue), encoding="utf-8", newline="\n")
    print(f"{action} {args.id}")
    return 0


def cmd_record(root: Path, args: argparse.Namespace) -> int:
    queue_path = root / QUEUE_REL
    queue = load_json(queue_path, {"version": 1, "items": []})
    item = find_item(queue, args.id)
    if item is None:
        print(f"unknown id: {args.id}", file=sys.stderr)
        return 2
    source_path = Path(args.source_file)
    if not source_path.is_file():
        print(f"source file not found: {source_path}", file=sys.stderr)
        return 2
    digest = sha256_file(source_path)
    previous = item.get("source_sha256")
    item["source_sha256"] = digest
    item["updated"] = today()
    if previous and previous != digest:
        item["status"] = "open"
        note = f"Source changed {today()} (hash {previous[:12]} → {digest[:12]})."
        existing_notes = item.get("notes") or ""
        item["notes"] = f"{existing_notes} {note}".strip()
        print(f"reopened {args.id}: source changed")
    else:
        print(f"recorded {args.id}: {digest}")
    write_json(queue_path, queue)
    (root / MARKDOWN_REL).write_text(render_markdown(queue), encoding="utf-8", newline="\n")
    return 0


def cmd_record_all(root: Path) -> int:
    surfaces_path = root / SURFACES_REL
    surfaces = load_json(surfaces_path, {"surfaces": []})
    queue_path = root / QUEUE_REL
    queue = load_json(queue_path, {"version": 1, "items": []})
    workspace = root.parent
    changed = 0
    for surface in surfaces.get("surfaces", []):
        rel = surface.get("source_file")
        if not rel:
            continue
        source_file = Path(rel)
        if not source_file.is_absolute():
            source_file = workspace / rel
        if not source_file.is_file():
            print(f"skip missing source: {source_file}", file=sys.stderr)
            continue
        item = find_item(queue, surface["id"])
        if item is None:
            print(f"skip unqueued surface: {surface['id']}", file=sys.stderr)
            continue
        digest = sha256_file(source_file)
        previous = item.get("source_sha256")
        item["source_sha256"] = digest
        item["updated"] = today()
        if previous and previous != digest:
            item["status"] = "open"
            note = f"Source changed {today()} (hash {previous[:12]} → {digest[:12]})."
            item["notes"] = f"{(item.get('notes') or '')} {note}".strip()
            print(f"reopened {surface['id']}")
            changed += 1
        else:
            print(f"unchanged {surface['id']}")
    write_json(queue_path, queue)
    (root / MARKDOWN_REL).write_text(render_markdown(queue), encoding="utf-8", newline="\n")
    print(f"record-all done; reopened={changed}")
    return 0


def cmd_render(root: Path) -> int:
    queue = load_json(root / QUEUE_REL, {"version": 1, "items": []})
    (root / MARKDOWN_REL).write_text(render_markdown(queue), encoding="utf-8", newline="\n")
    print(f"wrote {MARKDOWN_REL}")
    return 0


def cmd_list(root: Path) -> int:
    queue = load_json(root / QUEUE_REL, {"version": 1, "items": []})
    for item in queue.get("items", []):
        if item.get("status") != "open":
            continue
        print(f"{item.get('id')}\t{item.get('title')}\t{item.get('source_path')}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Localization work queue")
    parser.add_argument(
        "--root",
        default=None,
        help="core-assets repo root (default: two directories above this script)",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    add = sub.add_parser("add", help="Add or update a work item")
    add.add_argument("--id", required=True)
    add.add_argument("--title", required=True)
    add.add_argument("--kind", default="help-manual")
    add.add_argument("--status", default="open")
    add.add_argument("--priority", default="tier-1")
    add.add_argument("--source-repo", default="pim-offline-server")
    add.add_argument("--source-path", required=True)
    add.add_argument("--source-file", default=None, help="Local file to hash")
    add.add_argument("--product-route", default="")
    add.add_argument(
        "--required-tags",
        nargs="+",
        default=["de", "fr", "es", "en-GB", "zh-Hans"],
    )
    add.add_argument("--draft-tags", nargs="*", default=[])
    add.add_argument("--notes", default="")

    rec = sub.add_parser("record", help="Hash a source file; reopen if it changed")
    rec.add_argument("--id", required=True)
    rec.add_argument("--source-file", required=True)

    sub.add_parser("record-all", help="Rehash every surface in surfaces.json")
    sub.add_parser("render", help="Rewrite queue.md from queue.json")
    sub.add_parser("list", help="Print open item ids")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    script_dir = Path(__file__).resolve().parent
    root = Path(args.root).resolve() if args.root else script_dir.parents[1]
    if args.cmd == "add":
        return cmd_add(root, args)
    if args.cmd == "record":
        return cmd_record(root, args)
    if args.cmd == "record-all":
        return cmd_record_all(root)
    if args.cmd == "render":
        return cmd_render(root)
    if args.cmd == "list":
        return cmd_list(root)
    parser.error(f"unknown command {args.cmd}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
