<#
.SYNOPSIS
  Generate every derivative icon format from the canonical SVG / hi-res
  PNG sources in this `core-assets` repo.

.DESCRIPTION
  Per the workspace agent rule
  `c:\analog-pim\.cursor\rules\branding-assets.mdc`, derivative formats and
  resolutions of any branded asset MUST be produced INSIDE `core-assets`,
  not inside consumer projects. This script is the canonical raster /
  multi-resolution-ICO pipeline.

  Inputs (under this repo):
    - icons/source/aic-icon.svg          (vector master)
    - icons/source/aic-icon-1024.png     (1024x1024 raster master, used by
                                          `tauri icon` to populate
                                          icons/tauri/ -- see below)

  Outputs (under this repo, committed alongside source):
    - icons/desktop/aic-icon.ico         (multi-res Windows icon)
    - icons/desktop/aic-icon-preview.png (hero render for About dialogs)
    - icons/web/favicon.svg              (kept in sync with source)
    - icons/web/apple-touch-icon.svg
    - icons/web/logo.svg
    - icons/web/manifest.json

  After regenerating, run:
    - scripts/sync-to-projects.ps1       (push the new derivatives into
                                          every consumer project listed in
                                          its asset map)

  Tauri platform icons (Square*Logo.png, AppIcon-*.png, ic_launcher*.png,
  src-tauri/icons/icon.ico, etc.) are produced by the official Tauri CLI;
  they are NOT generated by this script. To regenerate them in
  core-assets/icons/tauri/:

    tauri icon icons/source/aic-icon-1024.png --output icons/tauri

  See icons/tauri/README.md.

.PARAMETER UseInkscape
  Force the Inkscape backend even when ImageMagick is available.

.NOTES
  Requires ImageMagick (`magick`) for ICO assembly. PNG-only generation can
  fall back to Inkscape when ImageMagick is absent.
#>
param(
    [switch] $UseInkscape
)

$ErrorActionPreference = "Stop"

$selfDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $selfDir "..")).Path

Write-Host "=== AIC core-assets icon generator ===" -ForegroundColor Cyan
Write-Host "Repo root: $repoRoot"

$hasImageMagick = [bool] (Get-Command magick -ErrorAction SilentlyContinue)
$hasInkscape    = [bool] (Get-Command inkscape -ErrorAction SilentlyContinue)
if (-not $hasImageMagick -and -not $hasInkscape) {
    throw "Neither ImageMagick (`magick`) nor Inkscape found. Install one to continue."
}
$tool = if ($UseInkscape -and $hasInkscape) { "Inkscape" }
        elseif ($hasImageMagick) { "ImageMagick" }
        else { "Inkscape" }
Write-Host "Backend: $tool" -ForegroundColor Green

function Convert-SvgToPng([string] $svgPath, [string] $pngPath, [int] $size) {
    if ($tool -eq "ImageMagick") {
        & magick convert -background none -resize "${size}x${size}" $svgPath $pngPath 2>&1 | Out-Null
    } else {
        & inkscape $svgPath --export-filename=$pngPath --export-width=$size --export-height=$size 2>&1 | Out-Null
    }
    if ($LASTEXITCODE -ne 0) { throw "Failed to render $svgPath -> $pngPath ($size px)" }
    Write-Host ("  [ok] {0} ({1}x{1})" -f (Resolve-Path $pngPath).Path, $size) -ForegroundColor DarkGreen
}

# ---- Desktop ICO -----------------------------------------------------------

$srcSvg = Join-Path $repoRoot "icons/source/aic-icon.svg"
$desktopDir = Join-Path $repoRoot "icons/desktop"
New-Item -ItemType Directory -Force -Path $desktopDir | Out-Null

if (-not (Test-Path -LiteralPath $srcSvg)) {
    throw "Missing source SVG at $srcSvg."
}

Write-Host ""
Write-Host "Generating Windows multi-resolution ICO..." -ForegroundColor Yellow
$tempDir = Join-Path $env:TEMP "core-assets-icon-build"
New-Item -ItemType Directory -Force -Path $tempDir | Out-Null
try {
    $pngs = @()
    foreach ($sz in @(16, 24, 32, 48, 64, 128, 256)) {
        $p = Join-Path $tempDir "aic-icon-$sz.png"
        Convert-SvgToPng -svgPath $srcSvg -pngPath $p -size $sz
        $pngs += $p
    }
    if ($tool -eq "ImageMagick") {
        $icoOut = Join-Path $desktopDir "aic-icon.ico"
        & magick convert @pngs $icoOut 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "ICO assembly failed." }
        Write-Host "  [ok] $icoOut" -ForegroundColor Green
    } else {
        Write-Warning "ICO assembly requires ImageMagick. Skipping aic-icon.ico."
    }
}
finally {
    Remove-Item -LiteralPath $tempDir -Recurse -Force -ErrorAction SilentlyContinue
}

# ---- Preview PNG (used by About dialogs) -----------------------------------

Write-Host ""
Write-Host "Generating preview PNG..." -ForegroundColor Yellow
Convert-SvgToPng -svgPath $srcSvg -pngPath (Join-Path $desktopDir "aic-icon-preview.png") -size 256

# ---- Web SVGs are hand-authored; just sanity-check they exist --------------

Write-Host ""
Write-Host "Verifying web SVG sources..." -ForegroundColor Yellow
foreach ($f in @("favicon.svg", "apple-touch-icon.svg", "logo.svg", "manifest.json")) {
    $p = Join-Path $repoRoot "icons/web/$f"
    if (Test-Path -LiteralPath $p) {
        Write-Host "  [ok]  icons/web/$f" -ForegroundColor DarkGreen
    } else {
        Write-Warning "  Missing icons/web/$f -- create or copy from source SVG before sync."
    }
}

Write-Host ""
Write-Host "=== Icon generation complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Inspect the regenerated artefacts under icons/desktop/ and icons/web/."
Write-Host "  2. (Optional) Regenerate Tauri platform icons:"
Write-Host "       tauri icon icons/source/aic-icon-1024.png --output icons/tauri"
Write-Host "  3. Commit & push the new artefacts in this repo (core-assets)."
Write-Host "  4. Run scripts/sync-to-projects.ps1 to push them into every consumer project."
Write-Host "  5. For MSI shortcut variants (client/server, Win32/Tauri), also run:"
Write-Host "       scripts/generate-installer-shortcut-icons.ps1"
Write-Host ""
